# Generated by Django 4.1.1 on 2022-09-18 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('class_letter', models.CharField(max_length=1)),
                ('class_school_level', models.CharField(choices=[('PS', 'Primary school'), ('SS', 'Secondary school'), ('HS', 'High school')], default='PS', max_length=2)),
                ('class_teacher_name', models.CharField(max_length=20)),
                ('class_teacher_surname', models.CharField(max_length=20)),
                ('class_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
            ],
        ),
    ]
