# Generated by Django 4.1.1 on 2022-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
