# Generated by Django 4.1.1 on 2022-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_classes_class_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_photo',
            field=models.ImageField(default='../uploads/images/default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_school_level',
            field=models.CharField(choices=[('Primary school', 'Primary school'), ('Secondary school', 'Secondary school'), ('High school', 'High school')], default='Primary school', max_length=16),
        ),
    ]
