# Generated by Django 4.1.1 on 2022-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_classes_class_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_photo',
            field=models.ImageField(default='./uploads/images/default.jpg', null=True, upload_to='images'),
        ),
    ]
