# Generated by Django 4.1.1 on 2022-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_classes_class_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
    ]
