# Generated by Django 4.1.1 on 2022-09-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_type',
            field=models.CharField(choices=[('+', 'Add'), ('-', 'Subtract')], default='Subtract', max_length=1),
        ),
    ]
