# Generated by Django 4.1.1 on 2022-09-23 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_type',
            field=models.CharField(choices=[('+', 'Add'), ('-', 'Subtract')], default='+', max_length=1),
        ),
        migrations.CreateModel(
            name='SubtractPointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_log_date', models.DateField(auto_now_add=True)),
                ('points_log_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('points_log_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.classes')),
            ],
        ),
        migrations.CreateModel(
            name='AddPointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_log_date', models.DateField(auto_now_add=True)),
                ('points_log_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('points_log_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.classes')),
            ],
        ),
    ]
