# Generated by Django 4.1.1 on 2022-09-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_alter_pointslog_points_log_type_subtractpointslog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpointslog',
            old_name='points_log_amount',
            new_name='points_add_log_amount',
        ),
        migrations.RenameField(
            model_name='addpointslog',
            old_name='points_log_class',
            new_name='points_add_log_class',
        ),
        migrations.RenameField(
            model_name='addpointslog',
            old_name='points_log_date',
            new_name='points_add_log_date',
        ),
        migrations.RenameField(
            model_name='subtractpointslog',
            old_name='points_log_amount',
            new_name='points_subtract_log_amount',
        ),
        migrations.RenameField(
            model_name='subtractpointslog',
            old_name='points_log_class',
            new_name='points_subtract_log_class',
        ),
        migrations.RenameField(
            model_name='subtractpointslog',
            old_name='points_log_date',
            new_name='points_subtract_log_date',
        ),
    ]
