# Generated by Django 4.1.1 on 2022-09-26 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0014_alter_addpointslog_points_add_log_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpointslog',
            name='points_add_log_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subtractpointslog',
            name='points_subtract_log_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
