# Generated by Django 4.1.1 on 2022-10-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0015_alter_addpointslog_points_add_log_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_photo',
            field=models.ImageField(default="{% static 'favicon.ico' %}", null=True, upload_to='images'),
        ),
    ]
