# Generated by Django 4.1.1 on 2022-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_alter_classes_class_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
