# Generated by Django 4.1.1 on 2022-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0024_classes_class_remove_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_remove_photo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
