# Generated by Django 4.1.1 on 2022-10-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0026_alter_classes_class_remove_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_remove_photo',
        ),
    ]
