# Generated by Django 4.1.1 on 2022-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0027_remove_classes_class_remove_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
