# Generated by Django 4.1.1 on 2022-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0030_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_type',
            field=models.BooleanField(blank=True),
        ),
    ]
