# Generated by Django 4.1.1 on 2022-10-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0032_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtractpointslog',
            name='points_subtract_log_class',
        ),
        migrations.DeleteModel(
            name='AddPointsLog',
        ),
        migrations.DeleteModel(
            name='SubtractPointsLog',
        ),
    ]
