# Generated by Django 4.1.1 on 2022-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0034_alter_pointslog_points_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointslog',
            name='points_log_created_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pointslog',
            name='points_log_description',
            field=models.TextField(blank=True, help_text='Write some description if you need.', null=True),
        ),
    ]
