# Generated by Django 4.1.1 on 2022-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0037_alter_pointslog_points_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_photo',
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
