# Generated by Django 4.1.1 on 2022-11-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0041_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointslog',
            name='points_log_type',
        ),
    ]
