# Generated by Django 4.1.1 on 2022-11-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0042_remove_pointslog_points_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointslog',
            name='points_log_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
