# Generated by Django 4.1.5 on 2023-04-24 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0045_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_points',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_school_level',
            field=models.CharField(choices=[('Primary school', 'Primary school'), ('Secondary school', 'Secondary school'), ('High school', 'High school')], default='Secondary school', max_length=16),
        ),
    ]
