# Generated by Django 4.1.5 on 2023-05-01 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0046_alter_classes_class_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1, verbose_name='Litera klasy'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Numer klasy'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_points',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Punkty'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_school_level',
            field=models.CharField(choices=[('Primary school', 'Klasy początkowe'), ('Secondary school', 'Klasy średnie'), ('High school', 'Klasy starsze')], default='Secondary school', max_length=16, verbose_name='Poziom szkolnictwa'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_teacher_name',
            field=models.CharField(max_length=20, verbose_name='Imię wychowawczyni'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_teacher_surname',
            field=models.CharField(max_length=20, verbose_name='Nazwisko wychowawczyni'),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ilość punktów'),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='points.classes', verbose_name='Klasa rejestru'),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_created_by',
            field=models.CharField(max_length=30, null=True, verbose_name='Przez kogo zorbiony rejestr'),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data rejestru'),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_description',
            field=models.TextField(blank=True, help_text='Write some description if you need.', null=True, verbose_name='Opis rejestru'),
        ),
        migrations.AlterField(
            model_name='pointslog',
            name='points_log_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='Typ rejestru'),
        ),
    ]
