# Generated by Django 4.1.5 on 2023-05-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0049_alter_classes_class_school_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointslog',
            name='points_log_description',
        ),
    ]
