# Generated by Django 4.1.5 on 2023-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0051_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
