# Generated by Django 4.1.5 on 2023-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0053_article_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
