# Generated by Django 4.1.5 on 2023-08-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0054_alter_article_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Zdjęcie')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(upload_to='', verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Nazwa tytułowa'),
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.photo'),
        ),
    ]
