# Generated by Django 4.1.5 on 2023-08-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0056_remove_article_photo_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Zdjęcie')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.article')),
            ],
        ),
    ]
