# Generated by Django 4.1.5 on 2023-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0057_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_school_level',
            field=models.CharField(choices=[('Klasy początkowe', -3), ('Klasy średnie', -3), ('Klasy starsze', -3)], default='Klasy średnie', max_length=16, verbose_name='Poziom szkolnictwa'),
        ),
    ]
