# Generated by Django 4.1.5 on 2023-08-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0058_alter_classes_class_school_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_school_level',
            field=models.CharField(choices=[('1-4', 'Klasy początkowe'), ('5-8', 'Klasy średnie'), ('9-12', 'Klasy starsze')], default='Klasy średnie', max_length=16, verbose_name='Poziom szkolnictwa'),
        ),
    ]
