# Generated by Django 4.1.5 on 2023-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0045_alter_pointslog_points_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_start_date', models.DateField()),
                ('tournament_end_date', models.DateField()),
                ('tournament_is_active', models.BooleanField(default=False)),
                ('tournament_classes', models.ManyToManyField(to='points.classes')),
            ],
        ),
    ]
