# Generated by Django 4.1.5 on 2023-02-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('day_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_time', models.TimeField()),
                ('battle_is_finished', models.BooleanField(default=False)),
                ('battle_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentday')),
            ],
        ),
    ]
