# Generated by Django 4.1.5 on 2023-02-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentday_tournamentbattle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentday',
            old_name='day_tournament',
            new_name='tournament',
        ),
    ]
