# Generated by Django 4.1.5 on 2023-03-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_rename_day_tournament_tournamentday_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbattle',
            name='battle_first_oponent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
    ]
