# Generated by Django 4.1.5 on 2023-03-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentbattle_battle_first_oponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentBattle',
        ),
    ]
