# Generated by Django 4.1.5 on 2023-03-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_delete_tournamentbattle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_time', models.TimeField()),
                ('battle_is_finished', models.BooleanField(default=False)),
                ('battle_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentday')),
                ('battle_first_oponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
