# Generated by Django 4.1.5 on 2023-04-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0045_alter_pointslog_points_log_type'),
        ('tournaments', '0009_alter_tournamentbattle_battle_first_oponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_classes',
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_first_oponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_oponent', to='points.classes'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_second_oponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_oponent', to='points.classes'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='points.classes'),
            preserve_default=False,
        ),
    ]
