# Generated by Django 4.1.5 on 2023-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0045_alter_pointslog_points_log_type'),
        ('tournaments', '0010_remove_tournament_tournament_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_classes',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_classes',
            field=models.ManyToManyField(related_name='classes', to='points.classes'),
        ),
    ]
