# Generated by Django 4.1.5 on 2023-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_remove_tournament_tournament_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbattle',
            name='winner',
            field=models.TextField(blank=True, choices=[], max_length=15, null=True),
        ),
    ]
