# Generated by Django 4.1.5 on 2023-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_tournamentbattle_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbattle',
            name='winner',
            field=models.TextField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
