# Generated by Django 4.1.5 on 2023-05-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournamentbattle_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbattle',
            name='winner',
            field=models.TextField(blank=True, choices=[('FO', 'First opponent'), ('SO', 'Second opponent')], max_length=50, null=True),
        ),
    ]
