# Generated by Django 4.1.5 on 2023-05-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0049_alter_classes_class_school_level'),
        ('tournaments', '0014_alter_tournamentbattle_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_classes',
            field=models.ManyToManyField(related_name='classes', to='points.classes', verbose_name='Uczestniczące klasy'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_end_date',
            field=models.DateField(verbose_name='Data końca'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_is_active',
            field=models.BooleanField(default=False, verbose_name='Aktywny (tak/nie)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=100, verbose_name='Nazwa turnieju'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_start_date',
            field=models.DateField(verbose_name='Data początku'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentday', verbose_name='Dzień'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_first_oponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_oponent', to='points.classes', verbose_name='Pierwszy przeciwnik'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_is_finished',
            field=models.BooleanField(default=False, verbose_name='Pojedynek skończony'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_second_oponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_oponent', to='points.classes', verbose_name='Drugi przeciwnik'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='battle_time',
            field=models.TimeField(verbose_name='Czas pojedynku'),
        ),
        migrations.AlterField(
            model_name='tournamentbattle',
            name='winner',
            field=models.TextField(blank=True, choices=[('FO', 'Pierwszy przeciwnik'), ('SO', 'Drugi przeciwnik')], max_length=50, null=True, verbose_name='Zwycięzca'),
        ),
        migrations.AlterField(
            model_name='tournamentday',
            name='day_date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tournamentday',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Turniej'),
        ),
    ]
